vector_RL: 3

model:
  policy_model:
    ckpt: ./tasks/qa_feedback/model_outputs/t5-large-1k-train
    input_padding_side: right
    train_generation_kwargs:
      do_sample: True
      top_k: 20
      top_p: null
      temperature: 10.0
    eval_generation_kwargs:
      do_sample: False
      num_beams: 1
  value_model:
    ckpt: t5-base
    freeze_value_model: False
    policy_value_sharing: False
  

reward:
  relevance_model:
    ckpt: ./tasks/qa_feedback/model_outputs/rel_rm
    positive_reward: 0.3
    negative_reward: -0.3
  factuality_model:
    ckpt: ./tasks/qa_feedback/model_outputs/fact_rm
    positive_reward: 0.5
    negative_reward: -0.5
  completeness_model:
    ckpt: ./tasks/qa_feedback/model_outputs/comp_rm
    mean: -0.44677690555995353
    std: 8.301160619054132
    bias: 0.0
    scale: 0.3

env:
  max_input_len: 50
  max_generated_len: 100
  train_num_samples_per_input: 1

ppo:
  kl_coef: 0.3
  lam: 0.95
  gamma: 1.0
  pg_coef: 1.0
  vf_coef: 1.0
  cliprange: 0.2
  cliprange_value: 0.2
  whiten_rewards: True

train:
  total_episodes: 80000
  eval_interval: 5 #50
  sampling_batch_size_per_card: 1
  training_batch_size_per_card: 1 
  lr: 5.0e-5
  n_warmup_steps: 0
  n_ppo_epoch_per_rollout: 1
  kl_threshold: 10.0
  clip_grad: False
  max_grad_norm: 0.5
  seed: 42
  cuda_deterministic: True

logging:
  run_name: FG_vectorRL_sep_rew_const_lr_5e-5_temp_10_decoder_head
  wandb_log: False
  wandb_entity: rl-lang-fb
  wandb_project: FGHF_Vector_RL_Decoder_head
  log_interval: 1
  save_dir: ./tasks/qa_feedback/model_outputs/FG_vectorRL_sep_rew_const_lr_5e-5_temp_10_decoder_head