defaults:
  - _self_
  - logging: wandb
  - task: ultrafeedback
  - alg: ppo
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

experiment_name: tril_ultrafb_helpfulness_offlineRL

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
